---
title: "OTB temperature logger deployments"
author: 
   - name: Marcus Beck, <mbeck@tbep.org>, Sheila Scolaro, <sscolaro@tbep.org>
institute: "Tampa Bay Estuary Program"
date: "`r Sys.Date()`"
format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: 
      source: https://github.com/tbep-tech/otb-temp/blob/main/docs/tempeval.qmd
execute:
  echo: false
  warning: false
filters:
  - lightbox
  
lightbox: auto
---

```{r}
#| include: false
library(knitr)
library(here)
library(tidyverse)
library(sf)
library(plotly)
library(mapview)
library(leaflet)

load(file = here('data/metadat.RData'))
load(file = here('data/tempdat.RData'))

source(here('r/funcs.R'))

orgs <- metadat %>% 
  st_set_geometry(NULL) %>% 
  select(deploy_date, yr_site_logger) %>% 
  nest(.by = deploy_date) %>% 
  arrange(deploy_date) %>% 
  deframe() %>% 
  lapply(function(x) x$yr_site_logger)
```

::: {.panel-tabset}

## 2022

::: {.panel-tabset}

### Deploy 1

```{r}
ddin <- orgs[[1]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

### Deploy 2

```{r}
ddin <- orgs[[2]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

:::

## 2023

::: {.panel-tabset}

### Deploy 1

```{r}
ddin <- orgs[[3]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

### Deploy 2

```{r}
ddin <- orgs[[4]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

### Deploy 3

```{r}
ddin <- orgs[[5]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

Note: 3SWB3 is near the thermal discharge at Bartow Plant

### Deploy 4

```{r}
ddin <- orgs[[6]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

### Deploy 5

```{r}
ddin <- orgs[[7]]
tsplo_dd(tempdat, ddin)
mpplo_dd(metadat, ddin)
```

Note: Hurricane Idalia passage

:::
:::